# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  profile: "assertive"
  auto_title_instructions: |
    Format: <type>(<scope>): <subject>
    <scope> is optional
    Type: chore, docs, feat, fix, refactor, style, or test.
  fail_commit_status: true
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  sequence_diagrams: false
  suggested_reviewers: false
  poem: false
  auto_review:
    labels:
      - "!no bot reviewer"
  pre_merge_checks:
    docstrings:
      mode: off
    title:
      mode: off
language: "en-US"
