---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: 0.2
dictionaryDefinitions:
  - name: project-words
    path: ./.cspell/project-words.txt
    addWords: true
  - name: third-party-words
    path: ./.cspell/third-party-words.txt
    addWords: true
dictionaries:
  - project-words
  - third-party-words
useGitignore: true
ignorePaths:
  - /.cspell
